

// var milisec = 0
// var seconds = 0
// var minutes = 0
// var getHtmlmsec = document.getElementById('msec')
// var getHtmlsec = document.getElementById('sec')
// var getHtmlmin = document.getElementById('min')

// setInterval(function(){
//     milisec++
//     getHtmlmsec.innerHTML = milisec
//     if(milisec >= 100){
//         seconds++
//         getHtmlsec.innerHTML = seconds
//         milisec = 0
//     }



// },10)


// // TRY



// var milisec = 0
// var seconds = 0
// var minutes = 0
// var getHtmlmsec = document.getElementById('milisec')
// var getHtmlsec = document.getElementById('secs')
// var getHtmlmin = document.getElementById('mints')

// setInterval(function(){
//     milisec++
//     getHtmlmsec.innerHTML = milisec
//     if(milisec >= 100){
//         seconds++
//         getHtmlsec.innerHTML = seconds
//         milisec = 0
//     }



// },10)









let main(){
    let sum =0;let i;
    for (i=1;i<=50;i++)

}if (i%2 ==0){
    sum +=i;
}